root = "."
tmp_dir = "tmp"
testdata_dir = "testdata"

[build]
  # Core build configuration (most important)
  cmd = "go build -o ./main apps/backend/cmd/api/main.go"
  bin = "./main"

  # File inclusion/exclusion rules (critical for performance)
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "node_modules", "scripts/venv", "venv", ".env", "apps/frontend", "docs", "todos"]
  exclude_file = ["package.json", "package-lock.json", "bun.lockb", "yarn.lock", "pnpm-lock.yaml"]
  exclude_regex = ["_test.go", "\\.(js|jsx|ts|tsx|css|scss|sass|less|)$", "\\.config\\.(js|ts|mjs)$"]

  # Build timing and behavior
  delay = 1000
  rerun_delay = 500
  kill_delay = "0s"

  # Build output and logging
  log = "build-errors.log"
  exclude_unchanged = false
  stop_on_error = false

  # Advanced options (least critical)
  args_bin = []
  full_bin = ""
  include_dir = []
  include_file = []
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  send_interrupt = false
  follow_symlink = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
