run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags: []

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true


  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 2

  misspell:
    locale: US

  lll:
    line-length: 120

  goimports:
    local-prefixes: mcp-gateway

  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc

  gosec:
    excludes:
      - G304 # Potential file inclusion via variable - we need this for config files
    config:
      G101: # Look for hard coded credentials
        pattern: "(?i)(?:password|pass|secret|key|token|pwd).*?[=:].*?[\"'].*?[\"']"
      G104: # Audit errors not checked
        fmt: true

  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/gin-gonic/gin
          - github.com/golang-jwt/jwt/v5
          - github.com/google/uuid
          - github.com/jackc/pgx/v5
          - github.com/jackc/pgx/v5/stdlib
          - github.com/joho/godotenv
          - github.com/joho/godotenv/autoload
          - github.com/lib/pq
          - github.com/redis/go-redis/v9
          - github.com/stretchr/testify
          - github.com/testcontainers/testcontainers-go
          - github.com/testcontainers/testcontainers-go/modules/postgres
          - github.com/testcontainers/testcontainers-go/wait
          - github.com/ulule/limiter/v3
          - github.com/gorilla/websocket
          - golang.org/x/crypto/bcrypt
          - mcp-gateway

linters:
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - predeclared
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  disable: []

issues:
  exclude-files:
    - ".*\\.pb\\.go$"
  exclude-dirs:
    - vendor
    - apps/frontend/node_modules
    - scripts/venv
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - gocyclo
    - path: apps/backend/cmd/
      linters:
        - gochecknoinits
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    - text: "should not use dot imports"
      linters:
        - stylecheck

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
