server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s
  tls:
    enabled: false

database:
  host: "localhost"
  port: 5432
  database: "mcp_gateway_dev"
  username: "postgres"
  password: "postgres"
  schema: "public"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  max_lifetime: 1h

auth:
  access_token_expiry: 15m
  refresh_token_expiry: 7d
  api_key_expiry: 365d
  password_min_length: 8
  enable_registration: true
  require_email_verify: false

rate_limit:
  enabled: true
  storage: "memory"
  default_per_minute: 100
  default_per_hour: 2000
  default_per_day: 20000
  burst_multiplier: 2.0
  cleanup_interval: 1h
  key_prefix: "ratelimit:dev"

discovery:
  enabled: true
  health_check_interval: 30s
  health_check_timeout: 5s
  max_failures: 3
  recovery_time: 1m
  auto_discovery: false

logging:
  level: "debug"
  format: "text"
  output: "stdout"
  enable_audit: true
  enable_request: true
  request_body_log: true
  response_body_log: true
  max_body_size: 2048

redis:
  enabled: false
  host: "localhost"
  port: 6379
  database: 0
  max_retries: 3
  pool_size: 10
  pool_timeout: 30s

# MCP Discovery Service Configuration
mcp_discovery:
  enabled: true
  base_url: "https://metatool-service.jczstudio.workers.dev/search"

gateway:
  default_timeout: 30s
  max_concurrent_reqs: 500
  load_balance_strategy: "round_robin"
  circuit_breaker:
    enabled: true
    max_requests: 5
    interval: 30s
    timeout: 10s
    failure_threshold: 3
  proxy:
    buffer_size: 32768
    max_idle_conns: 50
    max_idle_conns_per_host: 5
    idle_conn_timeout: 90s
    disable_compression: false
