server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s
  tls:
    enabled: false

database:
  host: "localhost"
  port: 5432
  database: "mcp_gateway_dev"
  user: "postgres"
  password: "postgres"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  max_lifetime: 1h

auth:
  access_token_expiry: 15m
  refresh_token_expiry: 168h  # 7 days
  api_key_expiry: 8760h       # 365 days
  password_min_length: 8
  enable_registration: true
  require_email_verify: false

rate_limit:
  enabled: true
  storage: "memory"
  default_limit: 100
  default_window: 1m
  cleanup_interval: 1h

discovery:
  enabled: true
  health_interval: 30s
  failure_threshold: 3
  recovery_timeout: 1m

logging:
  level: "debug"
  environment: "development"
  backend: "file"
  buffer_size: 1000
  batch_size: 50
  flush_interval: 5s
  async: true
  config:
    path: "logs/mcp-gateway-dev.log"
    max_size: 52428800  # 50MB
    max_files: 10
    rotate: true
    permissions: "0644"
    buffer_size: 8192
    sync_interval: "5s"
  retention:
    days: 30
    policy: "time"
  
  format: "text"
  request_logging: true
  audit_logging: true
  metrics_enabled: true
  retention_days: 30

redis:
  enabled: false
  host: "localhost"
  port: 6379
  database: 0
  max_retries: 3
  pool_size: 10
  pool_timeout: 30s

# MCP Discovery Service Configuration
mcp_discovery:
  enabled: true
  base_url: "https://metatool-service.jczstudio.workers.dev/search"

gateway:
  proxy_timeout: 30s
  max_retries: 3
  load_balancer: "round_robin"
  circuit_breaker:
    enabled: true
    failure_threshold: 3
    recovery_timeout: 30s
    half_open_requests: 5
